language: java
jdk:
  -openjdk11

addons:
  sonarcloud:
    organization: "unimibsoftengcourse2021"
    token: ${SONAR_TOKEN}
script:
  -mvn clean org:jacoco:jacoco-maven-plugin:prepare_agent install sonar:sonar -Dsonar.projectKey=UnimibSoftEngCOurse2021_travis-exercise-Nasic-Elvis
